### ISSUE TITLE
Middleware is run after services are injected

### ISSUE THREAD

**Issue by j-rewerts** [jviau/durabletask-hosting#2]
I have a service that needs Durable Task middleware to be run prior to injecting it. It seems like services are always injected prior to middleware being run though. Is there a way for us to configure this?

**Comment by jviau** [comment]
This is due to resolving the activity/orchestration from DI in the middleware pipeline before any customer middleware is ran. So the ask here is to allow for inserting middleware at custom positions, in this case after the service scope is created, but before it is used to resolve the orchestration or activity.
